name: Compress SugarCode-VScodePlugin
on:
  push:
    paths:
      - "SugarCode-VScodePlugin/**"
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.2
        with:
          submodules: "recursive"
      - name: Compress SugarCode-VScodePlugin
        run: |
          cd SugarCode-VScodePlugin
          zip -r ../sugarcode.zip .
      - name: Commit SugarCode-VScodePlugin
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -m "[auto] zip SugarCode-VScodePlugin" -a || exit 0
          git push
