name: Publish SugarCode-VScodePlugin
on:
  push:
    paths:
      - 'SugarCode-VScodePlugin/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
        working-directory: SugarCode-VScodePlugin
      - name: Publish extension
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
        working-directory: SugarCode-VScodePlugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VSCE_TOKEN }}
